apiVersion: v1
kind: Service
metadata:
  name: cesium-api
  labels:
    app: cesium-api
  namespace: default
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
  selector:
    app: cesium-api