name: Docker Image CI and publish

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/auscalabledronecloud/cesium_api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ASDC_PACKAGES }}

      - name: Push image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: |
            ghcr.io/auscalabledronecloud/cesium_api:latest
            ${{ steps.meta.outputs.tags }}
          push: true
